services:
  - type: web
    name: polaris-view-components
    env: ruby
    region: ohio
    plan: starter
    branch: render
    numInstances: 2
    buildCommand: "./bin/render-build.sh"
    startCommand: "cd demo; bundle exec puma -C config/puma.rb"
    domains:
      - polarisviewcomponents.org
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MAX_THREADS
        value: 5
      - key: RAILS_SERVE_STATIC_FILES
        value: enabled
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
