source "https://rubygems.org"

ruby file: ".ruby-version"

gem "rails", "~> 7.1.3.2"
gem "puma", "~> 6.0"
gem "sqlite3"
gem "sprockets-rails"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "lookbook", "~> 2.0"

gem "polaris_view_components", path: "../"

group :development, :test do
  gem "foreman"
end

group :development do
  gem "listen"
  gem "web-console", ">= 4.1.0"
end
