source "https://rubygems.org"

ruby File.read(".ruby-version").chomp

gem "rails", "~> 7.0.2"
gem "puma", "~> 5.0"
gem "sprockets-rails"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "lookbook"

gem "polaris_view_components", path: "../"

group :development, :test do
  gem "foreman"
end

group :development do
  gem "web-console", ">= 4.1.0"
end
