# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative "config/application"

# TODO: Check later, fails with error:
# LoadError: cannot load such file -- /Users/kirillplatonov/Code/polaris_view_components/demo/lib/lookbook.rb
# Rails.application.load_tasks
